package gengine.events.generators;

import gengine.events.receivers.KeyboardEventReceiver;
import gengine.world.World;
import gengine.world.entity.WorldEntity;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 * KeyboardEventGenerator. Listens to KeyEvents generated by the game's JPanel,
 * and dispatches them throughout the world.
 *
 * @author Richard Kutina <kutinric@fel.cvut.cz>
 */
public class KeyboardEventGenerator extends AbstWindowEventGenerator {

    private static final Logger LOG = Logger.getLogger(KeyboardEventGenerator.class.getName());

    //TODO: possibly rewrite this thing to use some silly FIFO buffers to store the KeyEvents
    //      and then dispatch them one by one inside the work method
    //
    private final World world;
    private final JFrame jf;

    private final KeyListener kl = new KeyListener() {
        @Override
        public void keyTyped(KeyEvent e) {
            dispatchKeyEvent(e);
        }

        @Override
        public void keyPressed(KeyEvent e) {
            dispatchKeyEvent(e);
        }

        @Override
        public void keyReleased(KeyEvent e) {
            dispatchKeyEvent(e);
        }
    };

    public KeyboardEventGenerator(World world, JFrame jframe, int period) {
        super(world, jframe, period);
        this.world = world;
        this.jf = jframe;
    }

    @Override
    public void init() {
        //add a new KeyListener to the JFrame

        //TODO: check whether it's already attached
        //      might just as well set up a flag here for that... :/
        this.jf.addKeyListener(kl);
    }

    @Override
    public void work(long dt) {
        //periodically check the world entities hash
        //if it doesn't match, rebuild the event generator list?
        //somewhat pointless.
    }

    @Override
    public void die() {
        //detach KeyListener from the JFrame
        this.jf.removeKeyListener(kl);
    }

    private void dispatchKeyEvent(KeyEvent e) {
        synchronized (this.world) {
            WorldEntity[] worldEntities = this.world.getEntities();

            for (WorldEntity we : worldEntities) {
                if (we instanceof KeyboardEventReceiver) {
                    KeyboardEventReceiver receiver = (KeyboardEventReceiver) we;

                    switch (e.getID()) {
                        case KeyEvent.KEY_PRESSED: {
                            receiver.keyPressed(e);
                            break;
                        }
                        case KeyEvent.KEY_RELEASED: {
                            receiver.keyReleased(e);
                            break;
                        }
                        case KeyEvent.KEY_TYPED: {
                            receiver.keyTyped(e);
                            break;
                        }
                        default: {
                            LOG.severe("Unexpected KeyEvent ID! This is seriously fishy.");
                        }
                    }
                }
            }
        }

    }

}
